# YouTube Scam Ad Scanner - Configuration

# Scanner settings
DEFAULT_TIMEOUT = 10  # seconds
USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'

# Risk score thresholds
RISK_THRESHOLD_MINIMAL = 10
RISK_THRESHOLD_LOW = 25
RISK_THRESHOLD_MEDIUM = 50

# Scoring weights (how many points each indicator adds)
SCORE_SUSPICIOUS_TLD = 15
SCORE_LONG_DOMAIN = 10
SCORE_MULTIPLE_HYPHENS = 10
SCORE_MULTIPLE_DIGITS = 5
SCORE_NO_HTTPS = 10
SCORE_IP_ADDRESS = 20
SCORE_PER_SCAM_KEYWORD = 5
SCORE_PER_URGENCY_WORD = 3
SCORE_PER_TGTBT_PHRASE = 5
SCORE_EXCESSIVE_EXCLAMATION = 10
SCORE_POPUP_SCRIPT = 15
SCORE_MISSING_META = 5
SCORE_FEW_LINKS = 5
SCORE_PASSWORD_FIELD = 15
SCORE_SUSPICIOUS_FORM = 10
SCORE_REDIRECT = 5
SCORE_FETCH_FAILED = 10

# Feature flags
ENABLE_REDIRECT_DETECTION = True
ENABLE_FORM_ANALYSIS = True
ENABLE_SCRIPT_ANALYSIS = True
